name: CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    name: cargo fmt
    steps:
      - uses: actions/checkout@v4

      - name: install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt

      - name: cargo fmt
        run: cargo fmt --all --check

  test:
    runs-on: ubuntu-latest
    name: cargo clippy + test
    steps:
      - uses: actions/checkout@v4

      - name: install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy

      - name: cargo clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: cargo test
        run: cargo test

  check-benchmark:
    runs-on: ubuntu-latest
    name: cargo check bench
    steps:
      - uses: actions/checkout@v4

      - name: install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy

      - name: cargo clippy
        run: cargo clippy --all-targets --manifest-path=bench/Cargo.toml -- -D warnings
